### ISSUE TITLE
[ issue ] - Failed to set up installer: Missing appID parameter for package

### ISSUE THREAD

**Issue by xabru** [fyne-io/apps#1]
I have a problem running Fyne Apps Installer, I have followed the instructions and installed the prerequisites and when I run the command "fyne get fyne.io/apps" I get the following result "Failed to set up installer: Missing appID parameter for package".
How can I solve this problem?

**Comment by xabru** [comment]
Currently clone the repository and execute the application with the command "go run", but when I install an app from the fyne installer window I get the same error "Failed to set up installer: Missing appID parameter for package".

![image](https://user-images.githubusercontent.com/55867760/106043029-d4c0a080-60ab-11eb-8c9d-f66863e60389.png)

**Comment by andydotxyz** [comment]
Yes, sorry about this. It appears we have a bug on Windows :(

**Comment by andydotxyz** [comment]
If you can update to the latest version of this code on `master` the issue should be resolved :)
